# CMake generated Testfile for 
# Source directory: /nethome/tking88/spatter/tests
# Build directory: /nethome/tking88/spatter/build/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[parse_uniform_stride_1_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "parse_uniform_stride_1")
set_tests_properties([=[parse_uniform_stride_1_build]=] PROPERTIES  FIXTURES_SETUP "test_parse_uniform_stride_1_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_uniform_stride_1_test]=] "/nethome/tking88/spatter/build/tests/parse_uniform_stride_1")
set_tests_properties([=[parse_uniform_stride_1_test]=] PROPERTIES  FIXTURES_REQUIRED "test_parse_uniform_stride_1_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_uniform_stride_suite_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "parse_uniform_stride_suite")
set_tests_properties([=[parse_uniform_stride_suite_build]=] PROPERTIES  FIXTURES_SETUP "test_parse_uniform_stride_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_uniform_stride_suite_test]=] "/nethome/tking88/spatter/build/tests/parse_uniform_stride_suite")
set_tests_properties([=[parse_uniform_stride_suite_test]=] PROPERTIES  FIXTURES_REQUIRED "test_parse_uniform_stride_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_ms1_suite_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "parse_ms1_suite")
set_tests_properties([=[parse_ms1_suite_build]=] PROPERTIES  FIXTURES_SETUP "test_parse_ms1_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_ms1_suite_test]=] "/nethome/tking88/spatter/build/tests/parse_ms1_suite")
set_tests_properties([=[parse_ms1_suite_test]=] PROPERTIES  FIXTURES_REQUIRED "test_parse_ms1_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_custom_suite_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "parse_custom_suite")
set_tests_properties([=[parse_custom_suite_build]=] PROPERTIES  FIXTURES_SETUP "test_parse_custom_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_custom_suite_test]=] "/nethome/tking88/spatter/build/tests/parse_custom_suite")
set_tests_properties([=[parse_custom_suite_test]=] PROPERTIES  FIXTURES_REQUIRED "test_parse_custom_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_json_suite_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "parse_json_suite")
set_tests_properties([=[parse_json_suite_build]=] PROPERTIES  FIXTURES_SETUP "test_parse_json_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_json_suite_test]=] "/nethome/tking88/spatter/build/tests/parse_json_suite")
set_tests_properties([=[parse_json_suite_test]=] PROPERTIES  FIXTURES_REQUIRED "test_parse_json_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_run_config_suite_cpu_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "parse_run_config_suite_cpu")
set_tests_properties([=[parse_run_config_suite_cpu_build]=] PROPERTIES  FIXTURES_SETUP "test_parse_run_config_suite_cpu_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_run_config_suite_cpu_test]=] "/nethome/tking88/spatter/build/tests/parse_run_config_suite_cpu")
set_tests_properties([=[parse_run_config_suite_cpu_test]=] PROPERTIES  FIXTURES_REQUIRED "test_parse_run_config_suite_cpu_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_random_suite_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "parse_random_suite")
set_tests_properties([=[parse_random_suite_build]=] PROPERTIES  FIXTURES_SETUP "test_parse_random_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_random_suite_test]=] "/nethome/tking88/spatter/build/tests/parse_random_suite")
set_tests_properties([=[parse_random_suite_test]=] PROPERTIES  FIXTURES_REQUIRED "test_parse_random_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_concurrent_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "parse_concurrent")
set_tests_properties([=[parse_concurrent_build]=] PROPERTIES  FIXTURES_SETUP "test_parse_concurrent_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_concurrent_test]=] "/nethome/tking88/spatter/build/tests/parse_concurrent")
set_tests_properties([=[parse_concurrent_test]=] PROPERTIES  FIXTURES_REQUIRED "test_parse_concurrent_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_multilevel_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "parse_multilevel")
set_tests_properties([=[parse_multilevel_build]=] PROPERTIES  FIXTURES_SETUP "test_parse_multilevel_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_multilevel_test]=] "/nethome/tking88/spatter/build/tests/parse_multilevel")
set_tests_properties([=[parse_multilevel_test]=] PROPERTIES  FIXTURES_REQUIRED "test_parse_multilevel_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_size_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "parse_size")
set_tests_properties([=[parse_size_build]=] PROPERTIES  FIXTURES_SETUP "test_parse_size_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[parse_size_test]=] "/nethome/tking88/spatter/build/tests/parse_size")
set_tests_properties([=[parse_size_test]=] PROPERTIES  FIXTURES_REQUIRED "test_parse_size_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[standard_uniform_suite_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "standard_uniform_suite")
set_tests_properties([=[standard_uniform_suite_build]=] PROPERTIES  FIXTURES_SETUP "test_standard_uniform_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[standard_uniform_suite_test]=] "/nethome/tking88/spatter/build/tests/standard_uniform_suite")
set_tests_properties([=[standard_uniform_suite_test]=] PROPERTIES  FIXTURES_REQUIRED "test_standard_uniform_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[standard_ms1_suite_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "standard_ms1_suite")
set_tests_properties([=[standard_ms1_suite_build]=] PROPERTIES  FIXTURES_SETUP "test_standard_ms1_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[standard_ms1_suite_test]=] "/nethome/tking88/spatter/build/tests/standard_ms1_suite")
set_tests_properties([=[standard_ms1_suite_test]=] PROPERTIES  FIXTURES_REQUIRED "test_standard_ms1_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[concurrent_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "concurrent")
set_tests_properties([=[concurrent_build]=] PROPERTIES  FIXTURES_SETUP "test_concurrent_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[concurrent_test]=] "/nethome/tking88/spatter/build/tests/concurrent")
set_tests_properties([=[concurrent_test]=] PROPERTIES  FIXTURES_REQUIRED "test_concurrent_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[multilevel_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "multilevel")
set_tests_properties([=[multilevel_build]=] PROPERTIES  FIXTURES_SETUP "test_multilevel_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[multilevel_test]=] "/nethome/tking88/spatter/build/tests/multilevel")
set_tests_properties([=[multilevel_test]=] PROPERTIES  FIXTURES_REQUIRED "test_multilevel_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[binary-trace_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "binary-trace")
set_tests_properties([=[binary-trace_build]=] PROPERTIES  FIXTURES_SETUP "test_binary-trace_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[binary-trace_test]=] "/nethome/tking88/spatter/build/tests/binary-trace")
set_tests_properties([=[binary-trace_test]=] PROPERTIES  FIXTURES_REQUIRED "test_binary-trace_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[standard_suite_cpu_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "standard_suite_cpu")
set_tests_properties([=[standard_suite_cpu_build]=] PROPERTIES  FIXTURES_SETUP "test_standard_suite_cpu_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[standard_suite_cpu_test]=] "/nethome/tking88/spatter/build/tests/standard_suite_cpu")
set_tests_properties([=[standard_suite_cpu_test]=] PROPERTIES  FIXTURES_REQUIRED "test_standard_suite_cpu_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[standard_laplacian_suite_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "standard_laplacian_suite")
set_tests_properties([=[standard_laplacian_suite_build]=] PROPERTIES  FIXTURES_SETUP "test_standard_laplacian_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[standard_laplacian_suite_test]=] "/nethome/tking88/spatter/build/tests/standard_laplacian_suite")
set_tests_properties([=[standard_laplacian_suite_test]=] PROPERTIES  FIXTURES_REQUIRED "test_standard_laplacian_suite_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;85;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[standard_suite_gpu_build]=] "/usr/bin/cmake" "--build" "/nethome/tking88/spatter/build" "--target" "standard_suite_gpu")
set_tests_properties([=[standard_suite_gpu_build]=] PROPERTIES  FIXTURES_SETUP "test_standard_suite_gpu_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;70;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
add_test([=[standard_suite_gpu_hip_test]=] "/nethome/tking88/spatter/build/tests/standard_suite_gpu" "hip")
set_tests_properties([=[standard_suite_gpu_hip_test]=] PROPERTIES  FIXTURES_REQUIRED "test_standard_suite_gpu_fixture" _BACKTRACE_TRIPLES "/nethome/tking88/spatter/tests/CMakeLists.txt;78;add_test;/nethome/tking88/spatter/tests/CMakeLists.txt;0;")
