#!/usr/bin/env python3

# File:    testsuite.py
# Author:  Patrick Lavin
# Purpose: This script automates data collection and plot generation for
#          the testsuites that come included with Spatter.

import sys

available_tests = ["USTRIDE", "BWBW"]

def usage():
    print("Usage: ./testsuite <testsuite-name> <platform-name>")
    print("  testsuite-name: Choose a testsuite from [USTRIDE, BWBW]")
    print("  platform-name: Specify a name for the platform you are running on")
    sys.exit(1)

if __name__ == "__main__":
    if (len(sys.argv) != 3):
        print("Error: Wrong number of arguments")
        usage()

    testsuite = sys.argv[1]
    platform  = sys.argv[2]

    if (sys.argv[1] not in available_tests):
        print("Error: Testsuite {} not in list of available testsuites: {}".format(testsuite, available_tests))
        usage()

    #TODO: Check that the platform name does not conflict with the included dataset

    print("Running testsuite {} on platform {}".format(testsuite, platform))

