name: Build and Test Serial and OpenMP backends

on: 
  pull_request:
    branches: [main, spatter-devel]

jobs:
  build-and-run-serial:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build-Serial
      run: cmake -B build_serial_gnu -S . && make -C build_serial_gnu
    - name: Test-Serial
      run: make test -C build_serial_gnu

  build-and-run-omp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Build-OMP
      run: 
        cmake -DUSE_OPENMP=1 -B build_omp_gnu -S . && make -C build_omp_gnu
    - name: Test-OMP
      run: make test -C build_omp_gnu
