name: Build and Test HIP Backend

on:
  pull_request:
    branches: [main, spatter-devel]
  schedule:
    - cron: '30 8 * * *'

jobs:  
  build-hip:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Run batch file
      run: cd tests/misc && chmod +x run-crnch-hip.sh && sbatch run-crnch-hip.sh
      
