name: Build and Test Tenstorrent Backend

on:
  pull_request:
    branches: [main, spatter-devel]
  schedule:
    - cron: '30 8 * * *'

jobs:
  build-tenstorrent:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Run batch file
      run: cd tests/misc && chmod +x run-crnch-tenstorrent.sh && sbatch run-crnch-tenstorrent.sh
