name: Build and Test CUDA Backend

on:
  pull_request:
    branches: [main, spatter-devel]
  schedule:
    - cron: '30 8 * * *'

jobs:  
  build-cuda:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Run batch file
      run: cd tests/misc && chmod +x run-crnch-cuda.sh && sbatch run-crnch-cuda.sh
      
